version: '3.8'
services:
  db:
    # Use official Kartoza PostGIS image (production-ready)
    image: kartoza/postgis:17-3.5
    platform: linux/arm64
    environment:
      POSTGRES_USER: nndr
      POSTGRES_PASSWORD: nndrpass
      POSTGRES_DB: nndr_db
      # Basic PostGIS settings
      POSTGIS_ENABLE_OUTDB_RASTERS: "1"
      POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nndr -d nndr_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Optional: Add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/arm64
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nndr.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: nndr-network
    driver: bridge 