global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
# Prometheus itself
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

# PostgreSQL/PostGIS database
- job_name: 'postgres'
  static_configs:
  - targets: [ 'db:5432' ]
  metrics_path: /metrics
  scrape_interval: 30s

# Redis cache
- job_name: 'redis'
  static_configs:
  - targets: [ 'redis:6379' ]
  scrape_interval: 30s

# pgAdmin
- job_name: 'pgadmin'
  static_configs:
  - targets: [ 'pgadmin:80' ]
  scrape_interval: 60s

# Grafana
- job_name: 'grafana'
  static_configs:
  - targets: [ 'grafana:3000' ]
  scrape_interval: 60s
