-- public.os_open_names_staging definition

CREATE TABLE IF NOT EXISTS public.os_open_names_staging (
    id_text TEXT,
    names_uri TEXT,
    name1 TEXT,
    name1_lang TEXT,
    name2 TEXT,
    name2_lang TEXT,
    type TEXT,
    local_type TEXT,
    geometry_x TEXT,
    geometry_y TEXT,
    most_detail_view_res TEXT,
    least_detail_view_res TEXT,
    mbr_xmin TEXT,
    mbr_ymin TEXT,
    mbr_xmax TEXT,
    mbr_ymax TEXT,
    postcode_district TEXT,
    postcode_district_uri TEXT,
    populated_place TEXT,
    populated_place_uri TEXT,
    populated_place_type TEXT,
    district_borough TEXT,
    district_borough_uri TEXT,
    district_borough_type TEXT,
    county_unitary TEXT,
    county_unitary_uri TEXT,
    county_unitary_type TEXT,
    region TEXT,
    region_uri TEXT,
    country TEXT,
    country_uri TEXT,
    related_spatial_object TEXT,
    same_as_dbpedia TEXT,
    same_as_geonames TEXT,
    geom TEXT,
    source_name TEXT,
    upload_user TEXT,
    upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    batch_id TEXT,
    source_file TEXT,
    file_size BIGINT,
    file_modified TIMESTAMP,
    session_id TEXT,
    client_name TEXT
);
CREATE INDEX IF NOT EXISTS idx_os_open_names_staging_batch ON public.os_open_names_staging (batch_id);
CREATE INDEX IF NOT EXISTS idx_os_open_names_staging_session ON public.os_open_names_staging (session_id);
CREATE INDEX IF NOT EXISTS idx_os_open_names_staging_upload_time ON public.os_open_names_staging (upload_timestamp); 